# 使用 Python 基础镜像
FROM python:3.11-slim

# 设置工作目录
WORKDIR /app

# 复制代码到容器中
COPY backend .

# 安装依赖
# RUN pip install requirements.txt
RUN pip install --no-cache-dir fastapi uvicorn

# HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --start-interval=1s --retries=3 CMD [ "curl", "-f", "http://localhost:8000/health" ]

# 启动命令
CMD ["python", "src/main.py"]
