FROM python:3.11-slim
WORKDIR /app

# COPY backend/requirements.txt .
# RUN pip install -r requirements.txt
RUN pip install fastapi uvicorn
RUN pip install langchain_community langchain_core

COPY backend/src .

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --start-interval=1s --retries=3 CMD [ "curl", "-f", "http://localhost:7717/health" ]
EXPOSE 7717

CMD ["python", "main.py"]
